lib/rb_app_web/router.ex
defmodule RbAppWeb.Router do
  use RbAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]

  end

  scope "/", RbAppWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/about", AboutController
    resources "/feed", FeedController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  scope "/api", RbAppWeb do
    pipe_through :api

  end
end

lib/rb_app_web/controllers/feed_controller.ex
defmodule RbAppWeb.FeedController do
  use RbAppWeb, :controller

  alias RbApp.{ApiCalls, Websites}

  def index(conn, _params) do
    # Grabs List of News Source Website structs.
    sources = ApiCalls.get_website_sources()

    # Sends list of News Source Website structs to Websites Module to update websites table in the db.
    Websites.create_website(sources)

    # Grabs list of News Source Website structs from the websites table in the db.
    database_sources = Websites.list_news_sources()

    # Routes to index.html on /feed and sends the list of News Source Website structs as params.
    render(conn, "index.html", sources: database_sources)

    # database_languages = Websites.list_languages() # use for filter feature in the future project.
    # render(conn, "index.html", sources: database_sources, languages: database_languages ) # use for filter feature in the future project.
  end

  def show(conn, site) do
    # Grabs News Source Website struct from the db where id = id param, assigns struct to `db-source`
    db_source = Websites.get_site(%{"id" => Map.get(site, "id")})

    # Grabs List of News Source Article structs where News Source website_id = website_id param.
    headlines = ApiCalls.get_top_headlines(db_source.website_id)

    # Routes to headlines.html on /feed/website_id and sends the list of Article structs as params.
    render(conn, "headlines.html", headlines: headlines)
  end
end

lib/rb_app_web/views/feed_view.ex
defmodule RbAppWeb.FeedView do
    use RbAppWeb, :view

end

lib/rb_app_web/templates/feed/headlines.html.eex
<table>
  <thead>
    <tr>
      <td><h1>Top Headlines</h1> <%= link "Back to Sources", to: Routes.feed_path(@conn, :index), class: "button" %></td>
    </tr>
  </thead>
</table>

<table>
<thead>
    <tr>
      <th>Article Image</th>
      <th>Article Title</th>
      <th></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= for head <- @headlines do %>
        <tr>
            <td><img alt=" No Image to Display" src= <%= head.urlToImage %> /></td>
            <td><%= head.title %></td>
            <td><%=  %></td>
            <td><%= link "Read Article", to: head.url, class: "button" %></td>

        </tr>
    <% end %>
    </tbody>
</table>

lib/rb_app_web/templates/feed/index.html.eex
<section class="row">
  <h1>All News Outlets</h1>

</section>

<section class="row">

<table>
<thead>
    <tr>
      <th>News Source</th>
      <th></th>
      <th></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= for site <- @sources do %>
        <tr>
            <td><%=site.name %></td>
            <td></td>
            <td></td>
            <td><%= link "Top Headlines", to: Routes.feed_path(@conn, :show, site.website_id), class: "button" %> </td>

        </tr>
    <% end %>
    </tbody>
</table>
</section>
<section class="row">
  <article class="column">


  </article>
</section>